# Generated by Django 3.2.6 on 2023-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
                ('productstock', models.IntegerField(blank=True, default=0, null=True)),
                ('productdescrition', models.TextField()),
                ('productimage', models.ImageField(default='', upload_to='static/addproduct/image')),
            ],
        ),
    ]
