# Generated by Django 3.2.6 on 2023-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='productidnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
