# Generated by Django 3.2.6 on 2023-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0002_addproduct_productidnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorfield', models.TextField()),
                ('availabledoctor', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
