# Generated by Django 3.2.6 on 2023-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0003_bookappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productidnumber', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('productname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patientappoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('payment', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
