# Generated by Django 3.2.6 on 2023-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0004_orders_patientappoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappoint',
            name='patientname',
            field=models.CharField(max_length=100),
        ),
    ]
