# Generated by Django 3.2.6 on 2023-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0005_alter_patientappoint_patientname'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctoradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('specialization', models.IntegerField()),
                ('hospitalname', models.IntegerField()),
                ('address', models.IntegerField(blank=True, default=0, null=True)),
                ('fess', models.TextField()),
                ('doctorimage', models.ImageField(default='', upload_to='static/addproduct/image')),
            ],
        ),
    ]
