# Generated by Django 3.2.6 on 2023-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0006_doctoradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoradd',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctoradd',
            name='doctorimage',
            field=models.ImageField(default='', upload_to='static/doctor/image'),
        ),
        migrations.AlterField(
            model_name='doctoradd',
            name='fess',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctoradd',
            name='hospitalname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctoradd',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
    ]
