# Generated by Django 3.2.6 on 2023-04-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0007_auto_20230421_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='date',
        ),
    ]
