# Generated by Django 3.2.6 on 2023-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0008_remove_bookappointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappoint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patientappoint',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='patientappoint',
            name='time',
        ),
        migrations.AddField(
            model_name='patientappoint',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientappoint',
            name='doctorname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientappoint',
            name='doctorspecialization',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientappoint',
            name='slot',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
