# Generated by Django 3.2.6 on 2023-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addproduct',
        ),
    ]
