# Generated by Django 3.2.6 on 2023-04-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0013_addproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
