# Generated by Django 3.2.6 on 2023-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='doctorimage',
            field=models.ImageField(default='', upload_to='static/cart/image'),
        ),
    ]
