# Generated by Django 3.2.6 on 2023-04-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0016_cart_doctorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='doctorimage',
        ),
    ]
