# Generated by Django 3.2.6 on 2023-05-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0018_cart_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctoradd',
        ),
    ]
