# Generated by Django 3.2.6 on 2023-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0019_delete_doctoradd'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctoradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('hospitalname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('fess', models.IntegerField()),
                ('doctorimage', models.ImageField(default='', upload_to='static/doctor/image')),
            ],
        ),
    ]
