# Generated by Django 3.2.6 on 2023-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0020_doctoradd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='type',
            field=models.CharField(default='offline', max_length=100),
        ),
    ]
