# Generated by Django 3.2.6 on 2023-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0022_patientappoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappoint',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
