# Generated by Django 3.2.6 on 2023-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupproject', '0023_patientappoint_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifydoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
