# Generated by Django 5.1.2 on 2024-10-22 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupproject", "0024_verifydoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=40)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suppliername", models.CharField(blank=True, max_length=60)),
                ("contact", models.IntegerField()),
                ("email", models.EmailField(blank=True, max_length=155, unique=True)),
                ("address", models.TextField()),
                (
                    "supply_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="groupproject.product",
                    ),
                ),
            ],
        ),
    ]
