# Generated by Django 5.1.2 on 2024-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupproject", "0025_product_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="product",
        ),
        migrations.AddField(
            model_name="supplier",
            name="product",
            field=models.ManyToManyField(
                related_name="product", to="groupproject.product"
            ),
        ),
    ]
